{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
  {{- if .Values.global.imagePullSecrets }}
imagePullSecrets: {{ toYaml .Values.global.imagePullSecrets | nindent 2 }}
  {{- end }}
metadata:
  name: {{ template "cainjector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "cainjector.name" . }}
    chart: {{ template "cainjector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- end -}}
