{{- if or .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.controller.name | quote }}
  name: {{ template "nginx-ingress.serviceAccountName" . }}
{{- end -}}
