{{- if and .Values.rbac.create .Values.podSecurityPolicy.enabled .Values.defaultBackend.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.defaultBackend.name | quote }}
  name: {{ include "nginx-ingress.fullname" . }}-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nginx-ingress.fullname" . }}-backend
subjects:
  - kind: ServiceAccount
    name: {{ template "nginx-ingress.defaultBackend.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
