{{- if and .Values.defaultBackend.enabled  .Values.defaultBackend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.defaultBackend.name | quote }}
  name: {{ template "ingress-nginx.defaultBackend.serviceAccountName" . }}
{{- end }}
