{{- if .Values.tcp }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.controller.name | quote }}
  annotations:
{{ toYaml .Values.controller.tcp.annotations | indent 4}}
  name: {{ include "ingress-nginx.fullname" . }}-tcp
data:
{{ tpl (toYaml .Values.tcp) . | indent 2 }}
{{- end }}
