{{- if .Values.udp }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "nginx-ingress.name" . }}
    chart: {{ template "nginx-ingress.chart" . }}
    component: "{{ .Values.controller.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
{{ toYaml .Values.controller.udp.annotations | indent 4}}
  name: {{ template "nginx-ingress.fullname" . }}-udp
data:
{{ tpl (toYaml .Values.udp) . | indent 2 }}
{{- end }}
