description: Kibana
home: https://github.com/elastic/helm-charts
maintainers:
- email: michael.russell@elastic.co
  name: Michael Russell
name: kibana
version: 6.5.0
appVersion: 6.5.0
sources:
  - https://github.com/elastic/kibana
