{{ if .Values.query-frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos.componentname" (list $ "query-frontend") }}
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: query-frontend
{{ with .Values.query-frontend.deploymentLabels }}{{ toYaml . | indent 4 }}{{ end }}
  {{- with .Values.query-frontend.deploymentAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.query-frontend.autoscaling.enabled  }}
  replicas: {{ .Values.query-frontend.replicaCount | default 1 }}
  {{- end }}
  {{- with  .Values.query-frontend.strategy }}
  strategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "thanos.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: query-frontend
{{ with .Values.query-frontend.deploymentMatchLabels }}{{ toYaml . | indent 6 }}{{ end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "thanos.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: query-frontend
{{ with  .Values.query-frontend.labels }}{{ toYaml . | indent 8 }}{{ end }}
      {{- if or .Values.query-frontend.annotations .Values.query-frontend.metrics.annotations.enabled }}
      annotations:
      {{- end }}
      {{- with  .Values.query-frontend.annotations }}{{ toYaml . | nindent 8 }}{{- end }}
      {{- if .Values.query-frontend.metrics.annotations.enabled  }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.query-frontend.http.port }}"
      {{- end }}
    spec:
      containers:
      - name: thanos-query-frontend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.query-frontend.extraEnv }}
        env: {{ toYaml . | nindent 8 }}
        {{- end }}
        args:
        - "query-frontend"
        - "--log.level={{ .Values.query-frontend.logLevel }}"
        - "--log.format={{ .Values.query-frontend.logFormat }}"
        - "--http-address=0.0.0.0:{{ .Values.query-frontend.http.port }}"
        - "--query-range.partial-response"
        {{- if .Values.query-frontend.query-range.split-interval }}
        - "--query-range.split-interval"
        {{- end }}
        {{- if .Values.query-frontend.query-range.max-retries-per-request }}
        - "--query-range.max-retries-per-request"
        {{- end }}
        {{- if .Values.query-frontend.query-range.max-query-length }}
        - "--query-range.max-query-length"
        {{- end }}
        {{- if .Values.query-frontend.query-range.max-query-parallelism }}
        - "--query-range.max-query-parallelism"
        {{- end }}
        {{- if .Values.query-frontend.query-range.response-cache-max-freshness }}
        - "--query-range.response-cache-max-freshness"
        {{- end }}
        {{- if .Values.query-frontend.query-range.no-partial-response }}
        - "--no-query-range.partial-response"
        {{- end }}
        {{- if .Values.query-frontend.query-range.response-cache-max-freshness }}
        - "--query-range.response-cache-max-freshness"
        {{- end }}
        {{- if .Values.query-frontend.downstream-url }}
        - "--query-frontend.downstream-url"
        {{- end }}
        {{- if .Values.query-frontend.compress-responses }}
        - "--query-frontend.compress-responses"
        {{- end }}
        {{- if .Values.query-frontend.log_queries_longer_than }}
        - "--query-frontend.log_queries_longer_than"
        {{- end }}
        {{- if .Values.query-frontend.log.request.decision }}
        - "--log.request.decision"
        {{- end }}
        # TODO:
        # --tracing.config-file
        # --tracing.config
        # --query-range.response-cache-config-file
        # --query-range.response-cache-config
        {{- if .Values.query-frontend.extraArgs }}
        {{ toYaml .Values.query-frontend.extraArgs | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.query-frontend.http.port}}
        - name: grpc
          containerPort: {{ .Values.query-frontend.grpc.port }}
        resources:
          {{ toYaml .Values.query-frontend.resources | nindent 10 }}
        volumeMounts:
        {{- range .Values.query-frontend.serviceDiscoveryFileConfigMaps }}
        - mountPath: /etc/query-frontend/{{ . }}
          name: {{ . }}
        {{- end }}
        {{- if .Values.query-frontend.certSecretName }}
        - mountPath: /etc/certs
          name: {{ .Values.query-frontend.certSecretName }}
          readOnly: true
        {{- end }}
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: http
        readinessProbe:
          httpGet:
            path: /-/ready
            port: http
      volumes:
      {{- range .Values.query-frontend.serviceDiscoveryFileConfigMaps }}
      - name: {{ . }}
        configMap:
          defaultMode: 420
          name: {{ . }}
      {{- end }}
      {{- if .Values.query-frontend.certSecretName }}
      - name: {{ .Values.query-frontend.certSecretName }}
        secret:
          defaultMode: 420
          secretName: {{ .Values.query-frontend.certSecretName }}
      {{- end }}
      {{- with .Values.query-frontend.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.query-frontend.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.query-frontend.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.query-frontend.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with  (include "thanos.query-frontend.serviceaccount" . ) }}
      serviceAccountName: "{{ . }}"
      {{- end }}
{{ end }}
