{{- if .Values.global.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ include "webhook.name" . }}
    app.kubernetes.io/name: {{ include "webhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ template "cert-manager.chart" . }}
  name: {{ include "webhook.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
{{- include "podDisruptionBudget.spec" . | indent 2 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "webhook.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
