{{- if .Values.logstashConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: "{{ template "fullname" . }}"
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.logstashConfig }}
  {{ $path }}: |
{{- if (eq $path "logstash.yml") }}
    node.name: {{ template "fullname" $ }}
{{- end }}
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
