apiVersion: v2
name: ingress-nginx
# When the version is modified, make sure the artifacthub.io/changes list is updated
# Also update CHANGELOG.md
version: 4.1.0-beta.1
appVersion: 1.2.0-beta.1
home: https://github.com/kubernetes/ingress-nginx
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
keywords:
  - ingress
  - nginx
sources:
  - https://github.com/kubernetes/ingress-nginx
type: application
maintainers:
  - name: rikatz
  - name: strongjz
  - name: tao12345666333
engine: gotpl
kubeVersion: ">=1.19.0-0"
annotations:
  # Use this annotation to indicate that this chart version is a pre-release.
  # https://artifacthub.io/docs/topics/annotations/helm/
  artifacthub.io/prerelease: "true"
  # List of changes for the release in artifacthub.io
  # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx?modal=changelog
  artifacthub.io/changes: |
    - "Image and libraries updated"
    - "#8319  Upstream keepalive time"
    - "#8434  added new auth-tls-match-cn annotation"
    - "#8481  Fix log creation in chroot script"
    - "#8426	Bump github.com/prometheus/common from 0.32.1 to 0.33.0"
    - "#8444	replace deprecated topology key in example with current one"
    - "#8446	Fix suggested annotation-value-word-blocklist"
    - "#8219  Add keepalive support for auth requests"
    - "#8337	Jail/chroot nginx process inside controller container"
    - "#8455	Update dependencies"
    - "#8456	Implement object deep inspector"
    - "#8325	Fix for buggy ingress sync with retries"
    - "#8322	Improve req handling dashboard"
